WITH dados_base AS (
  SELECT PCPRODUT.CODPROD,
         PCPRODUT.DESCRICAO,
         PCEST.CODFILIAL,
         PCEST.QTESTGER,
         PCEST.QTPEDIDA
  FROM PCPRODUT
     , PCEST
     , PCFORNEC
     , PCCONSUM
     , PCPRODFILIAL
 WHERE PCPRODUT.CODPROD = PCEST.CODPROD
   AND PCEST.CODPROD = PCPRODFILIAL.CODPROD
   AND PCEST.CODFILIAL = PCPRODFILIAL.CODFILIAL
   AND PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
   AND ((PCPRODUT.CODFILIAL = PCEST.CODFILIAL) OR (PCPRODUT.CODFILIAL = '99') OR (PCPRODUT.CODFILIAL IS NULL))
   AND PCEST.CODFILIAL IN ('1','2','3','4','5','6','7','8')
   AND NVL(PCPRODUT.CODPRODPRINC, PCPRODUT.CODPROD) = PCPRODUT.CODPROD
   AND PCPRODUT.CODPROD = :CODPROD
)
SELECT 
    CODPROD,
    DESCRICAO,

    -- Estoque Atual por Filial
    MAX(CASE WHEN CODFILIAL = '1' THEN QTESTGER END) AS ESTOQUE_ATUAL_1,
    MAX(CASE WHEN CODFILIAL = '2' THEN QTESTGER END) AS ESTOQUE_ATUAL_2,
    MAX(CASE WHEN CODFILIAL = '3' THEN QTESTGER END) AS ESTOQUE_ATUAL_3,
    MAX(CASE WHEN CODFILIAL = '4' THEN QTESTGER END) AS ESTOQUE_ATUAL_4,
    MAX(CASE WHEN CODFILIAL = '5' THEN QTESTGER END) AS ESTOQUE_ATUAL_5,
    MAX(CASE WHEN CODFILIAL = '6' THEN QTESTGER END) AS ESTOQUE_ATUAL_6,
    MAX(CASE WHEN CODFILIAL = '7' THEN QTESTGER END) AS ESTOQUE_ATUAL_7,
    MAX(CASE WHEN CODFILIAL = '8' THEN QTESTGER END) AS ESTOQUE_ATUAL_8,

    -- Quantidade Pedida por Filial
    MAX(CASE WHEN CODFILIAL = '1' THEN QTPEDIDA END) AS QTPEDIDA_1,
    MAX(CASE WHEN CODFILIAL = '2' THEN QTPEDIDA END) AS QTPEDIDA_2,
    MAX(CASE WHEN CODFILIAL = '3' THEN QTPEDIDA END) AS QTPEDIDA_3,
    MAX(CASE WHEN CODFILIAL = '4' THEN QTPEDIDA END) AS QTPEDIDA_4,
    MAX(CASE WHEN CODFILIAL = '5' THEN QTPEDIDA END) AS QTPEDIDA_5,
    MAX(CASE WHEN CODFILIAL = '6' THEN QTPEDIDA END) AS QTPEDIDA_6,
    MAX(CASE WHEN CODFILIAL = '7' THEN QTPEDIDA END) AS QTPEDIDA_7,
    MAX(CASE WHEN CODFILIAL = '8' THEN QTPEDIDA END) AS QTPEDIDA_8

FROM dados_base
GROUP BY CODPROD, DESCRICAO
ORDER BY DESCRICAO;